Socketio
hatchways/team-dragonfruit pull request #58
Opened 2020-07-22 16:22 UTC by daniel-liemng

2020-07-22 23:16 UTC, aeciorc requested changes
Have a look at my comments. The best way to do this would be to have a different file in the server side that imports socket.io and exports two methods: `init` and message. `init` should take a server instance to setup the socket server. You can call it from www and pass the server. `notify` should take a userId + notification and pass it to them using io.to(socketId). In the same file you want to keep the Map between userId -> socketId (remember to remove userIds on 'disconnect'), which is how `notify` is able to find the socketId to send the messages. `message` can be imported and used in any route where that modifies the snippets. 

On the client side, you probably want a Notification Provider that wraps all protected routes. It should start the connection and listen to "notify" events. 

Btw, you also shouldn't ever have to refresh a page in the app

2020-07-22 23:16 UTC, aeciorc commented on client/src/components/Review.js
> +let socket = io.connect("http://localhost:3001");
You shouldn't establish the connection here. Otherwise the use won't be connected unless they go to this page. Instead, the user must be connected when they're on any protected routes

2020-07-22 23:16 UTC, aeciorc commented on client/src/components/Review.js
> +  };
You don't need sockets for this. Just make a regular request. It's the server who needs to emit the notification to the other user

2020-07-22 23:16 UTC, aeciorc commented on client/src/components/StripeInput.js
> +require("dotenv").config();
You don't need this here, do you?

2020-07-22 23:16 UTC, aeciorc commented on client/src/services/UserService.js
> +        return { errorMsg: { msg: "Error occured" } };
Shouldn't you be using authFetch for all of these requests?

2020-07-22 23:16 UTC, aeciorc commented on server/bin/www
> +
You don't need this

2020-07-22 23:16 UTC, aeciorc commented on server/bin/www
> +  });
You can get the user id from the token in the cookie like this: https://stackoverflow.com/a/33316122, so you don't need the currentUser event

2020-07-22 23:16 UTC, aeciorc commented on server/bin/www
> +  let map = new Map();
If you declare the map here, you'll be creating a new one on every connection.

2020-07-23 00:17 UTC, daniel-liemng commented on client/src/components/StripeInput.js
> +require("dotenv").config();
I deleted it. Previously, I used env var for STRIPE_API_KEY. But I decided to show the key, just hide the SECKET in the server> I forgot to delete

2020-07-24 17:09 UTC, merged